export class KaeConfig {
  // {"securityCode":"com.tencent.qqreaderiphone","uniqueKey":"","type":"2","clientId":""}
  static S_CLIENT_ID = "59a5c192dcbc36ea8f"
  static CLIENT_KEY = "4103c861a45f436b811597252ff5055c"
  static S_URL_MAIN1 ="https://tuicashier.youzan.com/wscshop/showcase/homepage?kdt_id=16719442&reft=1718042897154&spm=f.72119318"
  static S_URL_MAIN ="https://shop42618405.m.youzan.com/v2/showcase/homepage?kdt_id=42426237"
  // static S_URL_MAIN= "https://shop159882676.m.youzan.com/wscshop/showcase/homepage?kdt_id=159690508&reft=1717069328682&spm=f.140575848"
  // static S_URL_MAIN ="https://shop159882676.m.youzan.com/wscshop/showcase/homepage?kdt_id=159690508&reft=1717069328682&spm=f.140575848"
  // static S_URL_MAIN = "https://shop161868586.m.youzan.com/wscshop/showcase/homepage?kdt_id=161676418&sub_kdt_id=161676418"

}